Integrate gitlab
PM-Dungeon/desktop pull request #27
Opened 2022-02-05 11:31 UTC by Tobias321

Fixes #18

- Die `.github/workflows/test.yml` und die `.gitlab-ci.yml` verhalten sich jetzt gleich
- Der build step ist Voraussetzung für alle anderen Steps (im GH und GL)
- Wenn ein Fehler im build step auftritt, dann werden die Tests gar nicht erst gestartet
- Der artifacts step wird jedoch IMMER gestartet
- Man kann sich jetzt im GL ein Artefakt mit allen Ausgaben herunterladen:

![image](https://user-images.githubusercontent.com/85501570/152640076-b4f33392-4b86-4eb8-8b9f-fdf2eb63c786.png)

- Auch, wenn ein Test fehlschlug:

![image](https://user-images.githubusercontent.com/85501570/152640100-bbc87217-ffa4-4115-b75e-2b5aff4d03de.png)

- Schlägt jedoch der build step fehl, so kann man kein package mehr herunterladen, jedoch den fehlgeschlagenen build step herunterladen:

![image](https://user-images.githubusercontent.com/85501570/152640166-64bb5b13-d4d4-44d4-8eae-02218d7c877f.png)

2022-02-05 14:01 UTC, cagix commented
@Tobias321 great job 👍 

muss ich mir die ausgaben herunterladen, oder kann ich das auch online irgendwie sehen? und wenn ja, was genau kann ich da sehen?

2022-02-05 14:14 UTC, cagix reviewed
Du hast jetzt die Style-Checks abhängig von „build“ gemacht, ich dachte, die sollten eher parallel zu build laufen in einer eigenen stage?

In der GL-Config ist alles sehr ordentlich formatiert (mit Leerzeilen getrennt), könntest Du das bei der GH-Config auch einbauen?

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +        - gzip -k tests.txt
da würde ich lieber ein klassisches zip sehen, geht das? gz ist wieder nicht per default überall drauf afaik.

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +            - code/assemble.txt
das sollte dann noch ins .gitignore aufgenommen werden, oder?

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +            - code/junit.txt
das sollte dann noch ins .gitignore aufgenommen werden, oder?

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +            - code/spotbugsMain.txt
das sollte dann noch ins .gitignore aufgenommen werden, oder?

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +            - code/spotbugsTest.txt
das sollte dann noch ins .gitignore aufgenommen werden, oder?

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +            - code/checkstyle.txt
das sollte dann noch ins .gitignore aufgenommen werden, oder?

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +            - code/tests.txt
das sollte dann noch ins .gitignore aufgenommen werden, oder?

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +            - code/tests.txt
und bedeutet das, dass das gesamt-text-file auch online absehbar ist oder muss man das immer erst runterladen?

2022-02-05 14:14 UTC, cagix commented on .gitlab-ci.yml
> +        - gzip -k tests.txt
noch ein gedanke: scheinbar bietest du sowohl das reine textfile als auch die gepackte variante an. brauchen wir beides, also, wie gross werden diese textfiles so im mittel? dann könnte man auf die gepackte variante verzichten?

2022-02-05 15:03 UTC, Tobias321 commented
Das waren jetzt mehrere Fragen auf einmal:
- Das Artefakt muss nicht heruntergeladen werden, man kann denke ich auch einfach auf den Job klicken und sieht die Ausgaben, ich hoffe, dass das auch noch bei/nach der Dateiumleitung funktioniert (`> ... 2>&1`)
- Idee war aber, alle Log-Ausgaben in einer Textdatei zusammenzufassen (besserer Überblick)
- Die Artefakte werden von GL bereits gz-gepackt, also wäre `gzip -k tests.txt` tatsächlich nicht nötig
- Ein zip file wäre bestimmt auch möglich
- In den Log-Ausgaben steht entweder "alles ok" oder eine Fehlerbeschreibung (bei exit value 1)...
- Es wäre kein Problem, die Tests auch immer (also auch, wenn build fehlschlug) auszuführen
- Ja, zurzeit sind die Style-Checks auch abhängig von build, ohne build läuft der Rest zurzeit nicht
- Ich glaube, die GH-Config mag keine Leerzeilen, aber ich versuche es
- Ja, unsere Artefakt-Dateien sollten auch in der .gitignore aufgenommen werden

2022-02-05 16:46 UTC, cagix commented
> * Das Artefakt muss nicht heruntergeladen werden, man kann denke ich auch einfach auf den Job klicken und sieht die Ausgaben, ich hoffe, dass das auch noch bei/nach der Dateiumleitung funktioniert (`> ... 2>&1`)

Hast Du das mal geprüft?

> * Idee war aber, alle Log-Ausgaben in einer Textdatei zusammenzufassen (besserer Überblick)

Finde ich auch sehr gut, nur ich würde mir gern etwas online ansehen können, also nicht erst ein Artefakt runterladen und auspacken und öffnen müssen.

> * Die Artefakte werden von GL bereits gz-gepackt, also wäre `gzip -k tests.txt` tatsächlich nicht nötig

Ja, dann raus damit, oder?

> * Ein zip file wäre bestimmt auch möglich

1. Was passiert mit dem Text-File: Wird das von Gitlab beim Runterladen nochmal gezippt oder kriege ich da tatsächlich ein Text-File (bei Github wird es für den Download zwangsgepackt, da kommt man nicht drumrum)?

2. Wie groß ist das Text-File, also braucht man wirklich noch eine Zip-Version? Sonst würde ich das einfach weglassen.

> * In den Log-Ausgaben steht entweder "alles ok" oder eine Fehlerbeschreibung (bei exit value 1)...

D.h. ich sehe im Detail, welche JUnits rot und welche grün sind und ich sehe, welche Checks von Checkstyle nicht in Ordnung waren?

> * Es wäre kein Problem, die Tests auch immer (also auch, wenn build fehlschlug) auszuführen
> * Ja, zurzeit sind die Style-Checks auch abhängig von build, ohne build läuft der Rest zurzeit nicht

Naja, muss aber nicht. Macht ja Sinn, erstmal den Build zu machen und nur wenn der erfolgreich war, dann auch die JUnits anzuwerfen.

Ich meinte die Checks (Checkstyle, Spotbugs, ...). Die könnten doch eigentlich komplett unabhängig laufen?

Sollten dann die Checks einfach vor dem Build laufen? Die könnten eine eigene Stage bekommen ("Checks") und der Build läuft dann danach? Andererseits wird dann bei Formatierungsfehlern gar nicht erst gebaut, das ist auch etwas krude ...

2022-02-05 18:05 UTC, Tobias321 commented
> Hast Du das mal geprüft?

Nein, aber ich mache gleich nochmal eine GitLab-Runde :)

please be patient

2022-02-05 18:59 UTC, Tobias321 commented
@cagix die Lösung war: `tee` ;)

Ich hab folgendes geändert:
- `tee` für Ausgabe in Textdatei und Konsole
- -gzip
- Alle Test-Steps laufen jetzt immer (unabhängig, ob vorher der Build erfolgreich war)
- Update .gitignore

Passt jetzt alles, man kann in die Logs schauen oder sich das Artefakt herunterladen

Das Artefakt wird mit gzip gepackt, das ist eine Einstellungssache innerhalb von GL...

Hoffe, jetzt passt alles :)

Ach ja, die Log-Ausgaben sind ungepackt ca. 8 kb groß... Also eigentlich winzig.

2022-02-06 07:40 UTC, cagix commented
> - Alle Test-Steps laufen jetzt immer (unabhängig, ob vorher der Build erfolgreich war)

kannst du bitte "test" (junit) und "check" (checkstyle, spot...) unterscheiden?



> Passt jetzt alles, man kann in die Logs schauen oder sich das Artefakt herunterladen

👍


> Das Artefakt wird mit gzip gepackt, das ist eine Einstellungssache innerhalb von GL...

können wir das einstellen (also für das repo oder sogar die pipeline) oder ist das was, was nur der admin kann (quasi für alle)?



> Ach ja, die Log-Ausgaben sind ungepackt ca. 8 kb groß... Also eigentlich winzig

dann sollten wir auf ein extra packen verzichten. github macht das zwangsweise, das nervt kolossal...

2022-02-06 09:36 UTC, Tobias321 commented
> kannst du bitte "test" (junit) und "check" (checkstyle, spot...) unterscheiden?

So ungefähr:

![image](https://user-images.githubusercontent.com/85501570/152674910-d8d09fa3-6d6f-4863-b403-77bdc647a90d.png)

> können wir das einstellen (also für das repo oder sogar die pipeline) oder ist das was, was nur der admin kann (quasi für alle)?

Jetzt auf einmal ist es .zip, obwohl ich im GL nix geändert hatte...

> dann sollten wir auf ein extra packen verzichten. github macht das zwangsweise, das nervt kolossal...

Ja

Ich sehe das so, das GL ist unser "Fallback", wenn darüber die Studis die Abgaben machen, dann müssen wir entweder einmal auf den Job klicken oder wir laden das .zip herunter und müssen dieses entpacken... Es sind zwar zwei Schritte, aber, ich glaube, unvermeidbar ;)

2022-02-06 10:28 UTC, cagix commented
> > kannst du bitte "test" (junit) und "check" (checkstyle, spot...) unterscheiden?
> 
> So ungefähr:
> 
> ![image](https://user-images.githubusercontent.com/85501570/152674910-d8d09fa3-6d6f-4863-b403-77bdc647a90d.png)

ja, fast :)

```
       ---- build ---- test ----
     /                           \
start                             package
     \                           /
       ---- check --------------
```


> 
> > können wir das einstellen (also für das repo oder sogar die pipeline) oder ist das was, was nur der admin kann (quasi für alle)?
> 
> Jetzt auf einmal ist es .zip, obwohl ich im GL nix geändert hatte...

zip ist universeller, passt also. mir macht grad nur sorge, dass sich das einfach ändert, ohne dass du da was gemacht hast?!



> > dann sollten wir auf ein extra packen verzichten. github macht das zwangsweise, das nervt kolossal...
> 
> Ja
> 
> Ich sehe das so, das GL ist unser "Fallback", wenn darüber die Studis die Abgaben machen, dann müssen wir entweder einmal auf den Job klicken oder wir laden das .zip herunter und müssen dieses entpacken... Es sind zwar zwei Schritte, aber, ich glaube, unvermeidbar ;)

mir ging es nur darum, dass ich nicht zwangsweise erst was runterladen, auspacken und dann öffnen muss, sondern dass ich das auch direkt im browser anschauen kann. 

das mit dem runterladen ist nett, aber in meinen augen nicht wirklich notwendig. 

(notwendig wäre eine zusammenfassung der einzelnen logfiles, und zwar nicht einfach ein hintereinander-kopieren, sondern eine semantische zusammenfassung. aber das ist wohl zu kompliziert.)

2022-02-06 10:30 UTC, cagix commented
hmmm, noch ein gedanke: sollten wir "check" nach "style-check" oder so ähnlich umbenennen? ich hatte das immer als kurzschreibweise für check(style) gesehen, aber wenn man das auf die studis loslässt, wäre ein eindeutigerer name vielleicht besser?

2022-02-06 13:51 UTC, Tobias321 commented
Zwei Stages können nicht parallel laufen, ich hab nachgeschaut. Stages werden sequenziell ausgeführt, Jobs auf derselben Stage parallel (theoretisch, je nach Runner-Konfiguration, unser Runner hat "1"). Das ist das Prinzip der GL-CI.

Vorschlag: build-and-checkstyle, test (immer(?)), package (immer).

> (notwendig wäre eine zusammenfassung der einzelnen logfiles, und zwar nicht einfach ein hintereinander-kopieren, sondern eine semantische zusammenfassung. aber das ist wohl zu kompliziert.)

Das müsstest du bitte genauer beschreiben, ich kann mir unter "semantische Zusammenfassung" noch nix vorstellen.

Also noch mal kurz zusammengefasst:
- Man kann sich die Ausgabe jedes einzelnen Jobs anschauen,
- Man kann sich die Ausgabe aller Jobs zusammen anschauen oder als .zip-Datei herunterladen,
- Ich werde noch mal nach der Speicherdauer nachschauen oder Lutz fragen,
- Wir sollten nicht so viel Zeit mit dem Klein-Klein verlieren 😉

2022-02-06 16:51 UTC, cagix commented
> Zwei Stages können nicht parallel laufen, ich hab nachgeschaut. Stages werden sequenziell ausgeführt, Jobs auf derselben Stage parallel 

verstehe. hmmm.

> Vorschlag: build-and-checkstyle, test (immer(?)), package (immer).

build ist für thematisch was anderes als check. also lassen wir das so wie von dir vorgeschlagen. ich würde evtl. test vor check schieben, da inhaltliche fehler schwerer wiegen als style-fehler. was denkst du?

also build - test - check ...


> > (notwendig wäre eine zusammenfassung der einzelnen logfiles, und zwar nicht einfach ein hintereinander-kopieren, sondern eine semantische zusammenfassung. aber das ist wohl zu kompliziert.)
> 
> 
> 
> Das müsstest du bitte genauer beschreiben, ich kann mir unter "semantische Zusammenfassung" noch nix vorstellen.

naja ne art übersicht: junit: x tests grün, y tests rot, z% erfolgreich; checkstyle: verletzung von a, b und c ...

also eine zusammenfassung, aus der man direkt die punkte ableiten kann.

aber das wird wohl zu komplex sein, leider.



> - Wir sollten nicht so viel Zeit mit dem Klein-Klein verlieren 😉 

hast ja recht. sollte aber trotzdem ordentlich und verständlich sein.

2022-02-06 17:40 UTC, Tobias321 commented
> ich würde evtl. test vor check schieben, da inhaltliche fehler schwerer wiegen als style-fehler. was denkst du?
> 
> also build - test - check

gut, ok, build - test - check. vorher stand auch schon test vor check ;) ich ändere das wieder.

das mit den fehlern aus den log-ausgaben ableiten (semantische übersicht), bekomme ich nicht hin, aber die ausgaben von spot... und checkstyle sind auch so schon ganz nützlich. :)

2022-02-07 05:53 UTC, cagix requested changes
@Tobias321 Sieht gut aus 👍 

Bitte benenne die Outputdateien nicht einfach nur "output_X.txt", sondern irgendwie sinnvoll. Du kannst die Nummer gern voran stellen, damit das beim package-Job dann mit dem cat klappt. Beispiel: "01_build_log.txt", "02_junit_log.txt", ... "07_merge_log.txt".

2022-02-07 08:28 UTC, cagix approved these changes

2022-02-08 04:28 UTC, merged