Workflow: Transfer
PM-Dungeon/desktop pull request #31
Opened 2022-02-13 09:23 UTC by Tobias321

Fixes #29 

fixes #30 

Bitte hier noch schnell genehmigen, dann kann ich gl und muster nachziehen... :)

2022-02-13 09:41 UTC, cagix requested changes
lgtm

kannst du die jobs in gitlab_chi noch so benennen wie in github_ci?

2022-02-13 09:45 UTC, Tobias321 commented
> kannst du die jobs in gitlab_chi noch so benennen wie in github_ci?

ich weiß nicht, ob gitlab nicht dieses "-job" Suffix haben möchte oder ob das nur "Konvention" ist... sonst spräche eigentlich nix dagegen

2022-02-13 09:54 UTC, Tobias321 commented
> > kannst du die jobs in gitlab_chi noch so benennen wie in github_ci?
> 
> ich weiß nicht, ob gitlab nicht dieses "-job" Suffix haben möchte oder ob das nur "Konvention" ist... sonst spräche eigentlich nix dagegen

Ach, wir versuchen es einfach, wenn es nicht klappt, geht's hier in die nächste Iteration.

2022-02-13 15:06 UTC, cagix approved these changes
lgtm

@Tobias321 bitte **vor** dem
mergen im gitlab einmal testen!

2022-02-13 16:44 UTC, merged

2022-02-14 05:13 UTC, cagix commented
> Hat geklappt:

fein :)  manchmal ist gitlab bzgl. der namen etwas komisch, aber das betrifft afaik vor allem die stages -- bei den default-namen gelten leicht andere regeln als bei eigenen namen.