rework quickstart
PM-Dungeon/desktop pull request #59
Opened 2022-03-16 15:18 UTC by AMatutat

Fixes #44 #43 #40 

Ich habe die Dokumentation nochmal generalüberholt.
Bitte einmal Probelesen.
Ich habe dabei schon #58 beachtet und hab mich an die aktuelle `core` Version gehalten, der Release ist etwas outdated.

2022-03-16 16:06 UTC, cagix requested changes
Ja cool! Ein paar Kleinigkeiten ...

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Jenachdem welche Taste gedrückt wurde, ändern wie die (nächste) Position des Helden.
```suggestion
Je nachdem welche Taste gedrückt wurde, ändern wir die (nächste) Position des Helden.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +mit `level.getTileAt(newPosition.toCoordinate()).isAccessible()` können wir überprüfen, ob es sich bei der neuen Position um ein betretbares `Tile` handelt oder nicht.
```suggestion
Mit `level.getTileAt(newPosition.toCoordinate()).isAccessible()` können wir überprüfen, ob es sich bei der neuen Position um ein betretbares `Tile` handelt oder nicht.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Wenn Sie nun das Spiel starten, sollten Sie sich mit Ihren Helden bewegen können.
```suggestion
Wenn Sie nun das Spiel starten, sollten Sie Ihren Helden bewegen können.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Fügen Sie eine Animation für jede Laufrichtung hinzu.
```suggestion
Fügen Sie eine unterschiedliche Animation für jede Laufrichtung hinzu.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Dafür nutzen wir die `endFrame` Methode in `MyGame`. Mit `levelAPI.getCurrentLevel().isOnTile()` können wir überprüfen, ob unser Held auf dem EndTile steht. Ist dies der Fall, lassen wir ein neues Le
```suggestion
Dafür nutzen wir die `endFrame`-Methode in `MyGame`. Mit `levelAPI.getCurrentLevel().isOnTile()` können wir überprüfen, ob unser Held auf dem EndTile steht. Ist dies der Fall, lassen wir ein neues Level laden.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Da wir unseren Helden in `onLevelLoad` beim laden eines neuen Level automatisch neu platzieren, müssen wir uns darum nicht mehr kümmern.
```suggestion
Da wir unseren Helden in `onLevelLoad` beim Laden eines neuen Levels automatisch neu platzieren, müssen wir uns darum nicht mehr kümmern.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Starten Sie nun das Spiel sollten Sie sich mit Ihrem Helden durch das Level bewegen können und auch in das nächste Level gelangen können.
```suggestion
Starten Sie nun das Spiel, sollten Sie Ihren Helden durch das Level bewegen können und auch in das nächste Level gelangen können.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Das PM-Dungeon nutzt einen eigenen prozeduralen Levelgenerator. Eigentlich müssen Sie sich nicht damit beschäftigen, unter umständen kann die Brechnung von Level aber viel Zeit auf Ihrer Maschine ben
```suggestion
Das PM-Dungeon nutzt einen eigenen prozeduralen Levelgenerator. Eigentlich müssen Sie sich nicht damit beschäftigen, unter Umständen kann die Berechnung von Leveln aber viel Zeit auf Ihrer Maschine benötigen. Sie können daher auch abgespeicherte Level anstelle von "frisch generierten" Leveln verwenden. Fügen Sie dafür einfach `levelAPI.setGenerator(new LevelLoader());` zu Beginn der `MyGame#setup`-Methode hinzu. Die Level werden aus `.json` im `assets/level/files/`-Verzeichnis geladen.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Sie haben nun die ersten Schritte im Dungeon gemacht. Von nun an müssen Sie selbst entscheiden, wie Sie die Aufgaben im Praktikum umsetzten möchten. Ihnen ist mit Sicherheit aufgefallen, dass einige
```suggestion
Sie haben nun die ersten Schritte im Dungeon gemacht. Von nun an müssen Sie selbst entscheiden, wie Sie die Aufgaben im Praktikum umsetzen möchten. Ihnen ist mit Sicherheit aufgefallen, dass einige Interface-Methoden in diesem Dokument noch nicht erläutert wurden. Machen Sie sich daher mit der Javadoc des Frameworks vertraut.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Sie haben nun die ersten Schritte im Dungeon gemacht. Von nun an müssen Sie selbst entscheiden, wie Sie die Aufgaben im Praktikum umsetzten möchten. Ihnen ist mit Sicherheit aufgefallen, dass einige
Hier könnte ein Link auf das Framework platziert werden (also "Framework" könnte mit nem Link auf das Repo ergänzt werden)

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Schauen Sie in die Javadoc um herauszufinden, wie Sie optionale Räume identifizieren oder Wände wegsprengen können.
```suggestion
Schauen Sie in die [Javadoc](https://github.com/PM-Dungeon/core) um herauszufinden, wie Sie optionale Räume identifizieren oder Wände wegsprengen können.
```

2022-03-16 16:06 UTC, cagix commented on documentation/quickstart_de.md
> +Sie können noch weitere Parameter und Methoden verwenden, um den Sound Ihren Wünschen anzupassen. Schauen Sie dafür in die [`libGDX`-Dokumentation](https://libgdx.badlogicgames.com/ci/nightlies/docs/
```suggestion
Sie können noch weitere Parameter und Methoden verwenden, um den Sound Ihren Wünschen anzupassen. Schauen Sie dafür in die [`libGDX`-Dokumentation](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/audio/Sound.html).
```

2022-03-16 16:22 UTC, AMatutat commented on documentation/quickstart_de.md
> +- `getPosition` gibt an, wo unser Held im Dungeon steht. 
folgt weiter unten

2022-03-16 20:25 UTC, Tobias321 commented on documentation/quickstart_de.md
> +Dafür können Sie die Vorgaben entweder als Projekt in Ihrer IDE laden und die Anwendung über die Run-Funktion starten oder Sie starten die Anwendung über die Kommandozeile.
> Hier fehlt noch der Hinweis von @Tobias321, dass man in IJ am besten den `code`-Ordner aufmacht und nicht den Projektordner.

jap, das steht auch hier: https://github.com/PM-Dungeon/desktop/wiki/FAQ#problem--gradle-konfiguration-wird-nicht-erkannt

2022-03-16 20:26 UTC, AMatutat commented on documentation/quickstart_de.md
> +Dafür können Sie die Vorgaben entweder als Projekt in Ihrer IDE laden und die Anwendung über die Run-Funktion starten oder Sie starten die Anwendung über die Kommandozeile.
uh ich verlinke einfach darauf, dann lernen die studis direkt das wiki kennen.

2022-03-16 22:37 UTC, jedi101 commented on documentation/quickstart_de.md
> +Um das PM-Dungeon-Framework zu nutzen erstellen Sie sich einen Fork des [`desktop`-Repository](https://github.com/PM-Dungeon/desktop) und ziehen Sie sich einen lokalen Klon auf Ihr Gerät.
Um das PM-Dungeon-Framework zu nutzen erstellen Sie sich einen Fork des [`desktop`-Repository](https://github.com/PM-Dungeon/desktop) und ziehen sich einen lokalen Klon auf Ihr Gerät.

2022-03-16 22:39 UTC, jedi101 commented on documentation/quickstart_de.md
> +Um das PM-Dungeon-Framework zu nutzen erstellen Sie sich einen Fork des [`desktop`-Repository](https://github.com/PM-Dungeon/desktop) und ziehen Sie sich einen lokalen Klon auf Ihr Gerät.
Um das PM-Dungeon-Framework zu nutzen erstellen Sie sich einen Fork des [`desktop`-Repository](https://github.com/PM-Dungeon/desktop) und ziehen ~~Sie~~ sich einen lokalen Klon auf Ihr Gerät.

2022-03-16 22:55 UTC, jedi101 commented on documentation/quickstart_de.md
> +Die Methode `getTexture` müssen wir nun mit der Methode `getgetActiveAnimation` ersetzen. Ebenso ersetzen wir unser `texture`-Attribut durch ein Attribut `idle` (`private Animation idle`).
>Die Methode `getTexture` müssen wir nun mit der Methode ` ~~get~~getActiveAnimation` ersetzen. ...

Die Methode `getTexture` müssen wir nun mit der Methode `getActiveAnimation` ersetzen. ...

2022-03-16 22:59 UTC, jedi101 commented on documentation/quickstart_de.md
> +public Hero(SpriteBatch batch, Painter painter) {
194 -> public Hero(SpriteBatch batch, Painter painter)

Unsere Klasse heißt glaube ich "MyHero", der Konstruktor soltle demnach "MyHero" heißen.

2022-03-16 23:06 UTC, jedi101 commented on documentation/quickstart_de.md
> +Starten Sie nun das Spiel, sollten Sie Ihren Helden durch das Level bewegen können und auch in das nächste Level gelangen können.
Wenn Sie nun das Spiel starten, sollten Sie Ihren Helden durch das Level bewegen können und auch in das nächste Level gelangen.

2022-03-16 23:12 UTC, jedi101 commented on documentation/quickstart_de.md
> +Das PM-Dungeon nutzt einen eigenen prozeduralen Levelgenerator. Eigentlich müssen Sie sich nicht damit beschäftigen, unter Umständen kann die Berechnung von Leveln aber viel Zeit auf Ihrer Maschine b
... Die Level werden aus `.json`-Dateien im `assets/level/files/`-Verzeichnis geladen.

2022-03-16 23:19 UTC, jedi101 commented on documentation/quickstart_de.md
> +Sound bumSound = Gdx.audio.newSound(Gdx.files.internal("assets/sound/bum.mp3"));
bumSound klingt ein wenig nach Geräuschen die das Gesäß von sich geben kann =). Kann natürlich sein das der Held genau dieses Geräusch von sich geben soll dann hab ich nichts gesagt...

2022-03-16 23:23 UTC, jedi101 reviewed
Sieht soweit super aus. Für unnötig erachtete Kommentare von mir einfach ignorieren. 👍

2022-03-17 09:03 UTC, cagix commented
> Sieht soweit super aus. Für unnötig erachtete Kommentare von mir einfach ignorieren. 👍

@jedi101 Du kannst beim Review auf "Comment" clicken, wenn es nur ein Kommentar sein soll. Aber wenn Du Änderungen haben möchtest, wäre "Request Changes" der richtige Knopf. Wenn alles OK ist, dann einfach "Approve" -- nur dann wird der PR freigegeben. (und anschließend in allen Fällen "submit review" ...)

<img width="723" alt="Screenshot 2022-03-17 at 09 57 45" src="https://user-images.githubusercontent.com/20356276/158773847-c12ddeae-aece-47e8-bebd-1186ae2ccadd.png">

Und Du kannst @AMatutat die Arbeit leichter machen, indem Du ihm direkt eine Änderung vorschlägst. Dabei statt einfach nur einen Kommentar zu einer Code-Zeile zu tippern auf das "+-"-Symbol klicken. 

<img width="941" alt="Screenshot 2022-03-17 at 09 56 25" src="https://user-images.githubusercontent.com/20356276/158774457-33025c3a-36ee-4a12-a546-459384d8ca51.png">

Dann wird die Zeile in das Kommentarfeld übernommen und Du kannst innerhalb der Backticks direkt die Formulierung reintippern. Dann kann @AMatutat direkt auf "commit" drücken und den Vorschlag übernehmen :)

<img width="941" alt="Screenshot 2022-03-17 at 09 56 33" src="https://user-images.githubusercontent.com/20356276/158774478-bf8acf09-f57f-4e9b-9f40-5b741c7e0297.png">

2022-03-17 09:16 UTC, jedi101 commented
@cagix Soviel zu lernen und so wenig Zeit ^^ - Ich mach Euch hier echt mehr Arbeit als ich löse... Danke, werde ich nun so machen.

2022-03-17 09:43 UTC, cagix commented
> @cagix Soviel zu lernen und so wenig Zeit ^^ - Ich mach Euch hier echt mehr Arbeit als ich löse... Danke, werde ich nun so machen. Hab immer angst hier irgend etwas kaputt zu machen.

och, allet jut. dazu is ja dit praktikum da, oda?

2022-03-17 11:35 UTC, AMatutat commented
> och, allet jut. dazu is ja dit praktikum da, oda?

Wo ist mein Kaffee? :P 

@jedi101 alles gut.

2022-03-17 11:37 UTC, AMatutat commented on documentation/quickstart_de.md
> +Um das PM-Dungeon-Framework zu nutzen erstellen Sie sich einen Fork des [`desktop`-Repository](https://github.com/PM-Dungeon/desktop) und ziehen Sie sich einen lokalen Klon auf Ihr Gerät.
done

2022-03-17 11:37 UTC, AMatutat commented on documentation/quickstart_de.md
> +Die Methode `getTexture` müssen wir nun mit der Methode `getgetActiveAnimation` ersetzen. Ebenso ersetzen wir unser `texture`-Attribut durch ein Attribut `idle` (`private Animation idle`).
done

2022-03-17 11:38 UTC, AMatutat commented on documentation/quickstart_de.md
> +public Hero(SpriteBatch batch, Painter painter) {
stimmt, done

2022-03-17 11:38 UTC, AMatutat commented on documentation/quickstart_de.md
> +Starten Sie nun das Spiel, sollten Sie Ihren Helden durch das Level bewegen können und auch in das nächste Level gelangen können.
done

2022-03-17 11:39 UTC, AMatutat commented on documentation/quickstart_de.md
> +Das PM-Dungeon nutzt einen eigenen prozeduralen Levelgenerator. Eigentlich müssen Sie sich nicht damit beschäftigen, unter Umständen kann die Berechnung von Leveln aber viel Zeit auf Ihrer Maschine b
done

2022-03-17 11:40 UTC, AMatutat commented on documentation/quickstart_de.md
> +Sound bumSound = Gdx.audio.newSound(Gdx.files.internal("assets/sound/bum.mp3"));
renamed in `sound.mp3`

2022-03-17 11:42 UTC, cagix commented
> > och, allet jut. dazu is ja dit praktikum da, oda?
> 
> Wo ist mein Kaffee? :P
> 
> @jedi101 alles gut.

bin auf peter-jackson-kaffee umgestiegen :)  tee mit milch. ununterbrochen.

2022-03-17 11:43 UTC, AMatutat commented on documentation/quickstart_de.md
> +- `endFrame` wird am Ende jedes Frames aufgerufen. Hier werden später Abfragen und Berechnungen implementiert.  
done

2022-03-17 11:45 UTC, AMatutat commented on documentation/quickstart_de.md
> +- `getPosition` gibt an, wo unser Held im Dungeon steht. 
should be done

2022-03-17 11:47 UTC, AMatutat commented on documentation/quickstart_de.md
> +Dafür können Sie die Vorgaben entweder als Projekt in Ihrer IDE laden und die Anwendung über die Run-Funktion starten oder Sie starten die Anwendung über die Kommandozeile.
done.

2022-03-17 11:54 UTC, AMatutat commented
Habe das alte UML nochmal eingebunden. Dann kann ich später einen neuen PR mit upgedateten UML machen und muss nicht nochmal die Dokumentation anpacken.

2022-03-17 12:00 UTC, cagix commented
> Habe das alte UML nochmal eingebunden. Dann kann ich später einen neuen PR mit upgedateten UML machen und muss nicht nochmal die Dokumentation anpacken.

btw: das online-umlet ("umletino"?) erzeugt leider immer unscharfe abbildungen. in vscode gibt es jetzt auch ein umlet-plugin, das läuft richtig gut!

bitte immer beides, das `.uxf` und das `.png` in den bilder-ordner werfen.

2022-03-17 12:39 UTC, cagix requested changes
noch ein wenig Kleinkram, danach sind wir aber aus meiner Sicht da :)

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +Gehen Sie dafür in das `desktop/code` Verzeichnis und öffnen Sie die Kommandozeile und geben Sie folgenden Befehl ein:
```suggestion
Gehen Sie dafür in das `desktop/code`-Verzeichnis und öffnen Sie die Kommandozeile und geben Sie folgenden Befehl ein:
```

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +*Anmerkung: Wenn Sie Probleme beim Starten der Anwendung haben, schauen Sie in das [FAQ](https://github.com/PM-Dungeon/desktop/wiki/FAQ#problem--gradle-konfiguration-wird-nicht-erkannt).Sollten Sie I
```suggestion
_Anmerkung_: Wenn Sie Probleme beim Starten der Anwendung haben, schauen Sie in die [FAQ](https://github.com/PM-Dungeon/desktop/wiki/FAQ#problem--gradle-konfiguration-wird-nicht-erkannt).Sollten Sie Ihr Problem dennoch nicht lösen können, melden Sie sich bitte **frühzeitig** bei uns.
```

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +Öffnen Sie dafür das `desktop/code` Verzeichnis als Gradle-Projekt in Ihrer bevorzugten IDE.
```suggestion
Öffnen Sie dafür das `desktop/code`-Verzeichnis als Gradle-Projekt in Ihrer bevorzugten IDE.
```

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +Betrachten wir nun `desktop.MyGame.java`. Diese Klasse ist Ihr Einstiegspunkt in das Dungeon. Hier werden Sie später Ihre Inhalte erzeugen und in das Dungeon hinzufügen.
```suggestion
Betrachten wir nun `desktop.MyGame.java`. Diese Klasse ist Ihr Einstiegspunkt in den Dungeon. Hier werden Sie später Ihre Inhalte erzeugen und in den Dungeon hinzufügen.
```

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +`MyGame` erbt von `MainController`. Wie der Name schon vermuten lässt, ist der MainController die Haupt-Steuerung des Spiels. Er bereitet alles für den Start des Spieles vor, verwaltet die anderen Co
```suggestion
`MyGame` erbt von `MainController`. Wie der Name schon vermuten lässt, ist der MainController die Haupt-Steuerung des Spiels. Er bereitet alles für den Start des Spieles vor, verwaltet die anderen Controller und enthält die Game-Loop. Wir nutzen `MyGame`, um selbst in die Game-Loop einzugreifen und unsere eigenen Objekte wie Helden und Monster zu verwalten. Der `MainController` ist der Punkt, an dem alle Fäden des Dungeons zusammenlaufen.
```

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +Fangen wir damit an eine neue Klasse für den Helden anzulegen. Unser Held soll grafisch dargestellt werden und vom `EntityController` verwaltet werden können. Daher implementiert er das Interface `IE
```suggestion
Fangen wir damit an, eine neue Klasse für den Helden anzulegen. Unser Held soll grafisch dargestellt werden und vom `EntityController` verwaltet werden können. Daher implementiert er das Interface `IEntity`.
```

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +Wir müssen noch dafür sorgen, dass unser Held auch gezeichnet wird. Da unser Held später vom `EntityController`verwaltet wird, nutzen wir dafür die `update`-Methode.
```suggestion
Wir müssen noch dafür sorgen, dass unser Held auch gezeichnet wird. Da unser Held später vom `EntityController` verwaltet wird, nutzen wir dafür die `update`-Methode.
```

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +Wir haben die erste Version unseres Helden implementiert. Jetzt müssen wir ihn noch erstellen.
```suggestion
Wir haben die erste Version unseres Helden implementiert. Jetzt müssen wir ihn noch im Spiel instantiieren.
```

2022-03-17 12:39 UTC, cagix commented on documentation/quickstart_de.md
> +Das PM-Dungeon nutzt einen eigenen prozeduralen Levelgenerator. Eigentlich müssen Sie sich nicht damit beschäftigen, unter Umständen kann die Berechnung von Leveln aber viel Zeit auf Ihrer Maschine b
```suggestion
Das PM-Dungeon nutzt einen eigenen prozeduralen Levelgenerator. Eigentlich müssen Sie sich nicht damit beschäftigen, unter Umständen kann die Berechnung von Leveln aber viel Zeit auf Ihrer Maschine benötigen. Sie können daher auch abgespeicherte Level anstelle von "frisch generierten" Leveln verwenden. Fügen Sie dafür einfach `levelAPI.setGenerator(new LevelLoader());` zu Beginn der `MyGame#setup`-Methode hinzu. Die Level werden aus `.json`-Dateien im `assets/level/files/`-Verzeichnis geladen.
```

2022-03-17 12:57 UTC, cagix approved these changes
👍

2022-03-17 17:39 UTC, jedi101 approved these changes
Sieht jetzt richtig rund aus. 👍
Ich hätte noch ein paar hübsche Screenshots von dem Dungeon nach dem ich ihn basierend auf Deinem quickstart_de-Guide implementiert habe. (Falls bedarf besteht)

2022-03-18 11:45 UTC, merged