Update UML
PM-Dungeon/desktop pull request #60
Opened 2022-03-17 12:14 UTC by AMatutat

Fixes #45

Hinzugefügt wurden:
- `IEntity`
- `IAnimatable`
- `IHUDElement`

Dabei habe ich mich wieder auf die wesentlichen Inhalte beschränkt. Also das label "reduziert" trifft weiterhin zu.

2022-03-17 12:27 UTC, cagix requested changes
![simple_uml](https://user-images.githubusercontent.com/20356276/158807717-7d06e748-6b41-481a-b3e1-5407556b74a8.png)

- [ ] Das PNG ist unscharf. Bitte nicht mit Umletino machen, sondern mit der lokalen Java-Variante oder mit dem VSC-Plugin
- [ ] Liefern die "getTexture"-Methoden wirklich einen String? Sollte das nicht eine Texture sein? Oder wenigstens ein Path (und die Methoden sollten dann "getTexturePath" heissen?
- [ ] An zwei Stellen sind die Pfeile nicht sauber an die Klassen angedockt (siehe Screenshot)
- [ ] Sollten die Methoden update/contains/remove nicht in "AbstractController" sein? Das überschreiben doch HUDController und EntityController nicht wirklich, oder?
- [x] Sollten die IHUDElement und IEntity nicht auch ein gemeinsames Interface haben? Dann könnte auch die add-Methode von HUDController/EntityController in den AbstractController ...

2022-03-17 12:40 UTC, AMatutat commented
>  Sollten die Methoden update/contains/remove nicht in "AbstractController" sein? Das überschreiben doch HUDController und EntityController nicht wirklich, oder?

Wir verwenden Generics im Controller und die Studis kennen Generics zu diesem Zeitpunkt noch nicht. Darum hab ich etwas getrickst, um die Verständlichkeit zu erhalten.

> Sollten die IHUDElement und IEntity nicht auch ein gemeinsames Interface haben? Dann könnte auch die add-Methode von HUDController/EntityController in den AbstractController ...

Wäre ein Überlegung wert. Ich mach mal ein Issue auf. Diese Diskussion sollte jetzt nicht Teil dieses PR sein.

> Liefern die "getTexture"-Methoden wirklich einen String? Sollte das nicht eine Texture sein? Oder wenigstens ein Path (und die Methoden sollten dann "getTexturePath" heissen?

Ja tut es. Die Studis arbeiten nur mit Strings für die Texturen. Der magische `Painter` mach daraus dann eine Textur. Umbenennung in `getTexturePath` wäre denkbar, bin mir aber nicht sicher was ich davon halten soll. Diese Diskussion sollte jetzt nicht Teil dieses PR sein.

2022-03-17 12:56 UTC, AMatutat commented
>> Sollten die Methoden update/contains/remove nicht in "AbstractController" sein? Das überschreiben doch HUDController und EntityController nicht wirklich, oder?

> Wir verwenden Generics im Controller und die Studis kennen Generics zu diesem Zeitpunkt noch nicht. Darum hab ich etwas getrickst, um die Verständlichkeit zu erhalten.

Hab nix gesagt. Das gilt nur für `add`

2022-03-17 13:08 UTC, AMatutat commented
@cagix kann ich denn mit dem VS Code Plugin das ganze auch als png exportieren. Die Dokumentation vom Plugin gibt darüber keine Auskunft.

2022-03-17 16:51 UTC, cagix requested changes
sieht besser aus. die kante links bei IOnLevelLoader ist immer noch nicht mit dem kästchen "verknüpft": da ist jetzt ne lücke und der pfeil fehlt :)

2022-03-17 18:02 UTC, jedi101 requested changes
Wenn man es gaaaanz genau nimmt dockt der Vererbungspfeil von IAnimatable -> IEntity auch noch nicht so richtig an. Aber vom Inhalt her ist jetzt glaube ich alles drin was drin sein sollte. Mehr und es wäre glaube ich nicht mehr ein "simple"_uml Diagram. 
![uml](https://user-images.githubusercontent.com/33090297/158866278-ca1fc614-4ef2-4ca5-8d36-521e187550f2.PNG)

2022-03-18 11:43 UTC, AMatutat commented
>  da ist jetzt ne lücke und der pfeil fehlt :)

Lücke sollte jetzt weg sein. Pfeil fehlt da keiner, oder bin ich doof?

> Wenn man es gaaaanz genau nimmt dockt der Vererbungspfeil von IAnimatable -> IEntity auch noch nicht so richtig an.

jetzt (hoffentlich) doch

2022-03-18 13:06 UTC, jedi101 approved these changes
[deleted]

2022-03-18 14:58 UTC, cagix commented
> `![so-smooth-meme](https://user-images.githubusercontent.com/33090297/159008143-ef9aea5c-0545-47f9-b457-8fde897cf280.jpg)`

@jedi101 Bist Du im Besitz der nötigen Rechte, um dieses Bild hier zu veröffentlichen? Bitte immer dran denken: Dies ist ein öffentlich sichtbares Repo!

2022-03-18 17:16 UTC, jedi101 commented
@cagix Stimmt, diese Urheberrechts-Meme-Geschichte... Zukünftig nur noch Emojis (Solange die noch erlaubt sind).

2022-03-18 19:25 UTC, merged

2022-03-18 19:49 UTC, cagix commented
@AMatutat Echt jetzt? Ich muss ein Review für einen geschlossenen PR machen? 🤷😎🤣