Add figs to quickstart_de.md
PM-Dungeon/desktop pull request #62
Opened 2022-03-18 16:04 UTC by jedi101

Enhances quickstart_de.md as questioned in #61

2022-03-18 20:50 UTC, AMatutat commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_wasd.png)
hier würde ich die "wasd" Knöpfe rausnehmen, die sehen irgendwie out of place aus.

2022-03-18 20:53 UTC, AMatutat requested changes
Finde ich gut, ein paar Änderungswünsche habe ich trotzdem.  
@cagix ist unser Humor beauftragter, also sollte er auch nochmal gucken.

2022-03-18 20:53 UTC, AMatutat commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
Hier würde ich die HUD-Icons rausnehmen (die sind ja da noch nicht implementiert. 
Der "Sichtkegel" ist für mein Geschmack auch out of place.

2022-03-18 23:38 UTC, jedi101 commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_wasd.png)
*pff* - niemand mag meine NFTs... done.

2022-03-18 23:41 UTC, jedi101 commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
Sichtkegel. Das ist ganz klar ein "eins-A-Röntgenlaser" mit dem er sehen kann wo er sich befindet... HUD-Icons hab ich entfernt.

2022-03-20 08:08 UTC, cagix commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
hmmm, es könnte evtl. zu verwirrung führen, dass die studis denken, sie müssten den laserkegel auch implementieren... aber andererseits ist das vielleicht genau die art spielerische hervorhebung, die ihnen gefällt...

2022-03-20 08:10 UTC, cagix approved these changes
ich finde die bildchen recht verspielt, aber das könnte genau die art content sein, der auf der wellenlänge der studis liegt... insofern go for it, wenn's nicht ankommt, können wir es ja immer noch ändern/rausnehmen.

@jedi101 wie/womit hast du die bilder bemalt?

2022-03-20 12:16 UTC, jedi101 commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
@cagix 
* Es ist Sonntag, sollte man sich da nicht sonnen oder so? ^^
* Hm; Verwirrung stiften sollte das natürlich nicht. Wenn es zu Verwirrung bei den Studis führt ändern wir das, ganz klar.

2022-03-20 12:23 UTC, jedi101 commented
@cagix > wie/womit hast du die Bilder bemalt?

Habe dafür Photoshop benutzt. Die Sprechblasen und Grafiken liegen dort alle geordnet
in verschiedenen Layern, die bei Bedarf auch ausgeblendet/angepasst werden können. Einem ~~langweiligeren~~ seriöseren Darstellungsstil steht also nichts im Wege. (ein Klick)

2022-03-20 12:31 UTC, jedi101 commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
Haben wir vielleicht irgendwo einen "Alternative-Fakten" Ablageort wo ich die seriösere Form der Grafiken ablegen könnte, der nicht zum offiziellen Repo gehört aber auf das Ihr trotzdem dann zugriff habt für zukünftige Änderungen etc.? Dann lege ich die normalen Grafiken dort ab. Photoshop Dateien kann man ja auch mit freien Grafikbearbeitungsprogrammen (Gimp und co.) bearbeiten.

2022-03-20 13:47 UTC, cagix commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
> @cagix 
> 
> * Es ist Sonntag, sollte man sich da nicht sonnen oder so? ^^
> 
> * Hm; Verwirrung stiften sollte das natürlich nicht. Wenn es zu Verwirrung bei den Studis führt sollten wir das ändern.

ach lass mal, ich finde die bildchen eigentlich ganz nett, das lockert das ganze ein wenig auf. und ich glaube, den studis könnte das gut gefallen :)

2022-03-20 13:49 UTC, cagix commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
> Haben wir vielleicht irgendwo einen "Alternative-Fakten" Ablageort wo ich die seriösere Form der Grafiken ablegen könnte, der nicht zum offiziellen Repo gehört aber auf das Ihr trotzdem dann Zugriff habt für zukünftige Änderungen etc.? Dann lege ich die normalen Grafiken dort ab. Photoshop Dateien kann man ja auch mit freien Grafikbearbeitungsprogrammen (Gimp und co.) bearbeiten.

d.h. du bist mit photoshop unterwegs? ich würde im zweifel dann die photoshop-datei im selben ordner wie die abbildung ablegen. voraussetzung, es handelt sich nur um ein kilobyte...

2022-03-20 18:13 UTC, jedi101 commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
@cagix - Das ist leider so ein bisschen die Krux an Photoshopdateien. Ich weiß nicht genau warum aber die sind immer gleich so riesig. Die Paar Bilder auf den zwei, drei Layern haben schon fast 1MB, und das in einem Repo einzuchecken *hm*. Ich habe mal irgendwo gelesen, dass das nicht so schön ist. Aber klar, würde ich dann natürlich machen, wenn das auch noch in Ordnung wäre von der Größe her.

2022-03-21 04:43 UTC, cagix commented on documentation/quickstart_de.md
> +![first_start](figs/pm-dungeon_level_unknown.png)
> @cagix - Das ist leider so ein bisschen die Krux an Photoshopdateien. Ich weiß nicht genau warum aber die sind immer gleich so riesig. Die Paar Bilder auf den zwei, drei Layern haben schon fast 1MB, und das in einem Repo einzuchecken *hm*. Ich habe mal irgendwo gelesen, dass das nicht so schön ist. Aber klar, würde ich dann natürlich machen, wenn das auch noch in Ordnung wäre von der Größe her.

ja nee, das ist zu groß. überleg dir mal was und lass uns freitag drüber sprechen.

2022-03-21 20:15 UTC, jedi101 commented
@cagix - Würde ich liebend gerne aber eine Stimme aus dem Off sagt mir hier. "Du hast das Zauberwort nicht gesagt". 

>You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request.

2022-03-21 21:16 UTC, merged

2022-03-21 21:17 UTC, cagix commented
> @cagix - Würde ich liebend gerne aber eine Stimme aus dem Off sagt mir hier. "Du hast das Zauberwort nicht gesagt". 
> 
> 
> 
> >You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request.

blöd. erinnere mich, da nochmal wegen den berechtigungen zu schauen

2022-03-22 04:36 UTC, cagix commented
> > @cagix - Würde ich liebend gerne aber eine Stimme aus dem Off sagt mir hier. "Du hast das Zauberwort nicht gesagt".
> > > You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request.
> 
> blöd. erinnere mich, da nochmal wegen den berechtigungen zu schauen

tja, so kann es gehen ... @jedi101, du bist im team @PM-Dungeon/codemonkeys, was prinzipiell auf "write" steht. aber speziell für den `master` hatten wir am anfang mal diskutiert, dass nur die gruppen @PM-Dungeon/core und (später dann noch) @PM-Dungeon/teachingassistents in den `master` pushen dürfen, um den kreis der personen mit schreibzugriff auf `master` deutlich zu beschränken. das hatte einerseits aspekte der qualitätskontrolle aber auch die geschichte mit der lizenz im blick, damit nichts im `master` landet, was in irgendeiner form nicht kompatibel mit cc by-sa oder urheberrecht o.ä. ist.

@AMatutat was denkst du? wir könnten das beibehalten, dann müsste @jedi101 den assignee "abgeben" und an dich oder @Tobias321 setzen. oder wir packen @jedi101 noch mit zu den @PM-Dungeon/teachingassistents, was dann aber wieder die idee mit der "kontrolle" aufweichen würde?

2022-03-22 05:34 UTC, Tobias321 commented
> @AMatutat was denkst du? wir könnten das beibehalten, dann müsste @jedi101 den assignee "abgeben" und an dich oder @Tobias321 setzen. oder wir packen @jedi101 noch mit zu den @PM-Dungeon/teachingassistents, was dann aber wieder die idee mit der "kontrolle" aufweichen würde?

Ich kann mergen (bzw. squashen), wenn ich Assignee bin. Durch die Reviewer gibt es ja auch eine zusätzliche "Sicherheitsebene". Auch, wenn es unfair klingt, würde ich die @PM-Dungeon/codemonkeys und @PM-Dungeon/teachingassistents unverändert lassen. Aber das ist nur meine Meinung.

2022-03-22 05:40 UTC, cagix commented
> > @AMatutat was denkst du? wir könnten das beibehalten, dann müsste @jedi101 den assignee "abgeben" und an dich oder @Tobias321 setzen. oder wir packen @jedi101 noch mit zu den @PM-Dungeon/teachingassistents, was dann aber wieder die idee mit der "kontrolle" aufweichen würde?
> 
> Ich kann mergen (bzw. squashen), wenn ich Assignee bin. Durch die Reviewer gibt es ja auch eine zusätzliche "Sicherheitsebene". Auch, wenn es unfair klingt, würde ich die @PM-Dungeon/codemonkeys und @PM-Dungeon/teachingassistents unverändert lassen. Aber das ist nur meine Meinung.

genau, weil du in @PM-Dungeon/teachingassistents bist :) ...

aber das war ursprünglich auch der gedanke, dass man dadurch nochmal eine art sicherheitsnetz hat, bevor irgendwas im `master` und damit dauerhaft im repo landet. insofern würde ich das auch eher nicht aufweichen wollen, zumal man dann konsequenterweise das ja auch auf die anderen teammitglieder aufweiten müsste.

so, mal sehen, was @AMatutat davon hält. ansonsten wäre dann eben der workflow, dass @jedi101 für seine pr's dann @Tobias321 als assignee setzt, sobald die reviews "grün" sind (vorher nicht, da ja ggf. nochmal was überarbeitet werden muss).

2022-03-22 08:08 UTC, jedi101 commented
> ...Tobias321 als assignee setzt, sobald die reviews "grün" sind (vorher nicht, da ja ggf. nochmal was überarbeitet werden muss).

@cagix 
Also ich persönlich fände mehr Kontrolle durch strikte Zugriffsbeschränkungen des Repos besser. Die Lösung mit dem Setzen des Assignees auf Tobias321 sobald alles soweit passen sollte, fände ich gut.  (Just my two cents).

2022-03-22 11:46 UTC, AMatutat commented
@cagix ich soll meine Machtposition teilen? 
Auf der einen Seite haben wir die Regeln aus guten Grund, auf der anderen Seite sehe ich keinen Grund @jedi101 jetzt anders zu behandeln als die anderen (also die non-tobi SHks)

2022-03-22 11:55 UTC, jedi101 commented
@AMatutat - Zuviel Verantwortung, ich musste hier unterschreiben das ich keinen Blödsinn baue sonst wird das teuer. Und bezugnehmend auf
>Das schult auch den Workflow der in Unternehmen üblich ist.

... fänd ich echt besser.