First work in progress update to quickstart_en
PM-Dungeon/desktop pull request #63
Opened 2022-03-21 15:21 UTC by jedi101

Fixes #41.

Still, a work in progress because my English is not the yellow from the egg.

2022-03-22 10:28 UTC, jedi101 commented on documentation/quickstart_en.md
> +The **{specifications/defaults/presets/requirements}** are already executable and can be run directly.
Welche Verwendung für die "Vorgaben" des repos passt hier am besten?

2022-03-22 10:29 UTC, jedi101 commented on documentation/quickstart_en.md
> +Now before we implement our hero we should understand how exactly the **{specifications/defaults/presets/requirements}** are **{structured/built}**.
Was sollten wir hier für die Verwendung der repo "Vorgaben" verwenden?

2022-03-22 10:50 UTC, cagix commented on documentation/quickstart_en.md
> +The **{specifications/defaults/presets/requirements}** are already executable and can be run directly.
Gute Frage, da habe ich ad hoc auch kein passendes Wort. Wie wäre es mit einer Umschreibung: "The given files are ..." oder  "The given project is already ..."?

2022-03-22 10:51 UTC, cagix commented on documentation/quickstart_en.md
> +The **{specifications/defaults/presets/requirements}** are already executable and can be run directly.
> Gute Frage, da habe ich ad hoc auch kein passendes Wort. Wie wäre es mit einer Umschreibung: "The given files are ..." oder "The given project is already ..."?

Edit: Oder "The files given in the desktop repo ..."?

2022-03-22 10:53 UTC, cagix commented on documentation/quickstart_en.md
> +Now before we implement our hero we should understand how exactly the **{specifications/defaults/presets/requirements}** are **{structured/built}**.
"Now, before we implement our hero, we should understand how the sample project and the given code is structured."?

2022-03-22 10:54 UTC, cagix commented
für ein anständiges review fehlt mir die woche die zeit ... :/

2022-03-24 11:29 UTC, jedi101 commented on documentation/quickstart_en.md
> +Now before we implement our hero we should understand how exactly the **{specifications/defaults/presets/requirements}** are **{structured/built}**.
Fixed in: bce4b70

2022-03-24 11:29 UTC, jedi101 commented on documentation/quickstart_en.md
> +The **{specifications/defaults/presets/requirements}** are already executable and can be run directly.
Fixed in: bce4b70

2022-03-25 06:01 UTC, jedi101 commented on documentation/quickstart_en.md
> +// play the sound very dimmed
```suggestion
// play the sound at a volume level of 10%
```

2022-03-31 15:11 UTC, AMatutat requested changes
hab zweimal quer gelesen. 
Das ist mir aufgefallen:

2022-03-31 15:11 UTC, AMatutat commented on documentation/quickstart_en.md
> +- `beginFrame` is called at the beginning of each frame. Queries and calculations, such as combat situations, will be implemented here later.
```suggestion
- `beginFrame` is called at the beginning of each frame. Queries and calculations, such as combat situations, will be implemented here.
```

2022-03-31 15:11 UTC, AMatutat commented on documentation/quickstart_en.md
> +- `EndFrame` is called at the end of each frame. This is where queries and calculations, such as collision checks, are later implemented.
```suggestion
- `EndFrame` is called at the end of each frame. This is where queries and calculations, such as collision checks, are implemented.
```

2022-03-31 15:11 UTC, AMatutat commented on documentation/quickstart_en.md
> +  `OnLevelLoad` is called whenever a level is loaded. This is where monsters and items are created later, which are initially distributed in the level.
```suggestion
  `OnLevelLoad` is called whenever a level is loaded. This is where monsters and items are created, which are initially distributed in the level.
```

2022-03-31 15:11 UTC, AMatutat commented on documentation/quickstart_en.md
> +When you start the game now, you should be able to see your (rather immobile) hero in the dungeon.
```suggestion
When you now start the game , you should be able to see your (rather immobile) hero in the dungeon.
```

2022-03-31 15:11 UTC, AMatutat commented on documentation/quickstart_en.md
> +We now need to replace the `getTexture` method with the `getActiveAnimation` method. Similarly, we replace our `texture` attribute with an attribute `idle` (`private animation idle`).
```suggestion
We now need to replace the `getTexture` method with the `getActiveAnimation` method. Similarly, we replace our `texture` attribute with an attribute `idle` (`private Animation idle`).
```

2022-03-31 15:11 UTC, AMatutat commented on documentation/quickstart_en.md
> +You have now made the first steps in the dungeon. From now on, you have to decide for yourself how you want to implement the tasks in the lab. You will have noticed that some interface methods have n
```suggestion
You have now made the first steps in the dungeon. From now on, you have to decide for yourself how and what you want to implement in your dungeon. You will have noticed that some interface methods have not yet been explained in this document. Therefore, familiarise yourself with the Javadoc of the [Framework](https://github.com/PM-Dungeon/core).
```

2022-03-31 15:11 UTC, AMatutat commented on documentation/quickstart_en.md
> +Here you will find additional functions that you may need in the course of the practical course.
```suggestion
Here you will find additional functions that you may want to use. 
```

2022-03-31 15:16 UTC, cagix commented on documentation/quickstart_en.md
> +This document provides an introduction to the PM-Dungeon. It explains the installation of the framework and the first steps to add your own content to the dungeon. It serves as a basis for all furthe
finde ich gut. dann sind die dokumente zwar nicht mehr 1:1, aber das sollte die pflege leichter machen. außerdem passt das dann besser zu einer möglichen zielgruppe ...

mittelfristig bin ich am überlegen, ob man nicht die englische version in das core-repo zurückintegriert und das desktop-repo als template für das semester-repo umbaut. aber das sind gedanken für über-übermorgen-cagix.

2022-03-31 16:07 UTC, jedi101 commented on documentation/quickstart_en.md
> +When you start the game now, you should be able to see your (rather immobile) hero in the dungeon.
Da finde ich die ursprünglicher Ausdrucksweise fluenter. Im Deutschen würde man das sicher so schreiben aber ich glaube in Englisch... Was meinst Du, trotzdem ändern?

2022-03-31 16:08 UTC, jedi101 commented on documentation/quickstart_en.md
> +When you start the game now, you should see your animated (but still immobile) hero.
siehe Kommentar oben über diesem ^^

2022-03-31 16:19 UTC, AMatutat commented on documentation/quickstart_en.md
> +When you start the game now, you should be able to see your (rather immobile) hero in the dungeon.
alternativvorschlag: "now" einfach vollständig entfernen. Erfüllt eigentlich keinen zweck

2022-03-31 16:38 UTC, cagix commented on documentation/quickstart_en.md
> +When you start the game now, you should be able to see your (rather immobile) hero in the dungeon.
ja, "now" raus im zweifel. aber ich finde tatsächlich die urspr. variante "englischer" ... (bin aber kein experte)

2022-03-31 17:28 UTC, jedi101 commented
@AMatutat - Habe es wie besprochen editiert.

2022-04-02 10:45 UTC, AMatutat commented
@jedi101 ein paar Vorschläge sind noch offen. Nochmal rüber gucken. GitHub versteckt die auch ganz gerne hinter irgendwelchen "show more" buttons.

2022-04-03 11:33 UTC, jedi101 commented
@AMatutat -Soweit ich das überblicken kann sind nun alle Änderungen eingepflegt worden; auch die, die sich hinter dem "Show more" versteckt hatten. (Danke für den Hinweis)

2022-04-03 12:11 UTC, AMatutat approved these changes

2022-04-03 12:12 UTC, AMatutat commented
aus meiner Sicht dann eine brauchbare erste Version, rein damit.

2022-04-03 12:15 UTC, jedi101 commented
@AMatutat - Das "rein damit" müsstest Du übernehmen wenn es für eine erste Version soweit okay ist. Bin in der Gruppe "Coding Monkeys" und die haben dazu keine Rechte.

2022-04-03 13:39 UTC, merged